### Health Check
GET http://localhost:8090/health

### Check Token
GET http://localhost:8090/check
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlMjcyOTFjNC0xODhmLTRhY2EtYWE1Zi1kYzFkZmJmZWRmNzQiLCJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MzE0MDI3MDksImV4cCI6MTg4NjIzMTUwOX0.SDQnskZmG56Tq3Ysyw08TZXkNBpTrPsb1mPexRwRoDI

### Get Books
GET http://localhost:8090/books
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlMjcyOTFjNC0xODhmLTRhY2EtYWE1Zi1kYzFkZmJmZWRmNzQiLCJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MzE0MDI3MDksImV4cCI6MTg4NjIzMTUwOX0.SDQnskZmG56Tq3Ysyw08TZXkNBpTrPsb1mPexRwRoDI

### Create Book
POST http://localhost:8090/books
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlMjcyOTFjNC0xODhmLTRhY2EtYWE1Zi1kYzFkZmJmZWRmNzQiLCJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MzE0MDI3MDksImV4cCI6MTg4NjIzMTUwOX0.SDQnskZmG56Tq3Ysyw08TZXkNBpTrPsb1mPexRwRoDI

{
  "title": "Book 1",
  "author": "Author 1",
  "genre": "Genre 1"
}

### Update Book
PUT http://localhost:8090/books/14255dc9-dc3d-4c0d-b377-7fafbf31ed98
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlMjcyOTFjNC0xODhmLTRhY2EtYWE1Zi1kYzFkZmJmZWRmNzQiLCJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MzE0MDI3MDksImV4cCI6MTg4NjIzMTUwOX0.SDQnskZmG56Tq3Ysyw08TZXkNBpTrPsb1mPexRwRoDI

{
  "genre": "Genre 2",
  "rating": 5
}

### Delete Book
DELETE http://localhost:8090/books/48d60d77-0980-4bd4-9082-75e292469826
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlMjcyOTFjNC0xODhmLTRhY2EtYWE1Zi1kYzFkZmJmZWRmNzQiLCJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MzE0MDI3MDksImV4cCI6MTg4NjIzMTUwOX0.SDQnskZmG56Tq3Ysyw08TZXkNBpTrPsb1mPexRwRoDI

### Preflight
OPTIONS http://localhost:8090/books
