version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/auth-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/bookshelf-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/bookshelf_app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
